# Generated by Django 2.0.1 on 2018-04-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
