# Generated by Django 2.0.1 on 2018-04-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180414_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Coins'),
        ),
    ]
