# Generated by Django 2.0.1 on 2018-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180414_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
