# Generated by Django 2.0.1 on 2018-04-18 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django import forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20180414_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('creditcard',models.IntegerField(blank=True)),
                ('month',models.IntegerField(blank=True)),
                ('CV',models.IntegerField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='imgs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]