# Generated by Django 2.0.1 on 2018-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180420_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('ticker', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertransactions',
            unique_together={('username', 'ticker')},
        ),
    ]
