# Generated by Django 2.0.3 on 2018-04-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180420_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='CV',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='creditcard',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='month',
            field=models.IntegerField(max_length=4),
        ),
    ]
