# Generated by Django 2.0.3 on 2018-04-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180421_1628'),
        ('home', '0009_auto_20180421_0549'),
    ]

    operations = [
    ]
