# Generated by Django 2.0.1 on 2018-04-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20180421_1804'),
        ('home', '0013_auto_20180422_2017'),
    ]

    operations = [
    ]
