# Generated by Django 2.0.1 on 2018-04-25 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_merge_20180423_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactions_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertransactions_time',
            unique_together={('username', 'ticker', 'timestamp')},
        ),
    ]
