# Generated by Django 2.0.3 on 2018-04-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20180423_1322'),
        ('home', '0014_merge_20180423_1351'),
    ]

    operations = [
    ]
