# Generated by Django 2.0.1 on 2018-04-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180424_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
